/*  This file is automatically generated by utils/glue.sh,
 *  called from the configure script.  Do not edit by hand!
 */

#include "shntool.h"

extern mode_module mode_split;

mode_module *st_modes[] = {
  &mode_split,
  NULL
};
