/*  This file is automatically generated by utils/glue.sh,
 *  called from the configure script.  Do not edit by hand!
 */

#include "shntool.h"

extern format_module format_flac;
extern format_module format_ape;
extern format_module format_wav;
extern format_module format_wv;

format_module *st_formats[] = {
  &format_flac,
  &format_ape,
  &format_wav,
  &format_wv,
  NULL
};
